name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - develop-backend
  pull_request:
    branches:
      - master
      - develop-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permisson for gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend/

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ./backend/
